# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4500765f6a4c0663fadb2fbb802760eede20fd6976084eae4b723c09021a90462cfdc7d318c507cc6e5c2720082216ad181e1cee4b98cf9c08a16ef9bc7f9d0

test:
  secret_key_base: 3ab7dac67153792f774c33d8a2b31f3566f505c5e2461475d127bb5f098f24ee5b2acb04576e7e2847753e026b6483d4fe8ab8ec20fddfa03d56d4db123e71c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
